 --- #YAML:1.0
 name: Date-Holidays-AT
 abstract: Determining Austrian holidays in a given year.
 version: 0.1.0
 author:
   - Matthias Dietrich <perl@rainboxx.de>
 license: perl
 distribution_type: module
 requires:
   Date::Calc: 5.0
 recommends:
   YAML: 0.35
 build_requires:
   Test: 0
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: Module::Build version 0.26
