---
name: Date-Holidays-AT
version: v0.1.3
author:
  - 'Matthias Dietrich <perl@rainboxx.de>'
abstract: Determine Austrian holidays
license: perl
requires:
  Date::Calc: 5.0
  Test::More: 0
  version: 0
provides:
  Date::Holidays::AT:
    file: lib/Date/Holidays/AT.pm
    version: v0.1.3
generated_by: Module::Build version 0.26
